### ISSUE TITLE
Getting error : ValueError: 'create_entry' in __slots__ conflicts with class variable.

### ISSUE THREAD

**Issue by BSiddharth** [nvictus/priority-queue-dictionary#16]
Traceback:
> Traceback (most recent call last):
  File " ", line 4, in <module>
    from pqdict import PQDict 
  File " ", line 98, in <module>
    class PQDict(MutableMapping):
  File " ", line 85, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
ValueError: 'create_entry' in __slots__ conflicts with class variable

**Comment by BSiddharth** [comment]
Reinstalling the package solved the issue
